{
 "title": "Payment Monitoring — Real Time",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Failure Rate by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "ecommerce-data-platform-497218",
     "rawSql": "SELECT\r\n  window_start,\r\n  MAX(CASE WHEN gateway = 'stripe' THEN failure_rate END) AS stripe,\r\n  MAX(CASE WHEN gateway = 'paypal' THEN failure_rate END) AS paypal,\r\n  MAX(CASE WHEN gateway = 'mercadopago' THEN failure_rate END) AS mercadopago\r\nFROM (\r\n  SELECT\r\n    *,\r\n    ROW_NUMBER() OVER (\r\n      PARTITION BY window_start, gateway\r\n      ORDER BY _loaded_at DESC\r\n    ) AS rn\r\n  FROM `ecommerce-data-platform-497218.ecommerce_streaming.payment_metrics_5min`\r\n  WHERE window_start >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 MINUTE)\r\n)\r\nWHERE rn = 1\r\nGROUP BY window_start\r\nORDER BY window_start ASC"
    }
   ]
  },
  {
   "title": "Amount Processed by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "project": "ecommerce-data-platform-497218",
     "rawSql": "SELECT\r\n  window_start,\r\n  MAX(CASE WHEN gateway = 'stripe' THEN total_amount END) AS stripe,\r\n  MAX(CASE WHEN gateway = 'paypal' THEN total_amount END) AS paypal,\r\n  MAX(CASE WHEN gateway = 'mercadopago' THEN total_amount END) AS mercadopago\r\nFROM (\r\n  SELECT\r\n    *,\r\n    ROW_NUMBER() OVER (\r\n      PARTITION BY window_start, gateway\r\n      ORDER BY _loaded_at DESC\r\n    ) AS rn\r\n  FROM `ecommerce-data-platform-497218.ecommerce_streaming.payment_metrics_5min`\r\n  WHERE window_start >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 MINUTE)\r\n)\r\nWHERE rn = 1\r\nGROUP BY window_start\r\nORDER BY window_start ASC"
    }
   ]
  },
  {
   "title": "Total Payments by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "project": "ecommerce-data-platform-497218",
     "rawSql": "SELECT\r\n  window_start,\r\n  MAX(CASE WHEN gateway = 'stripe' THEN total_payments END) AS stripe,\r\n  MAX(CASE WHEN gateway = 'paypal' THEN total_payments END) AS paypal,\r\n  MAX(CASE WHEN gateway = 'mercadopago' THEN total_payments END) AS mercadopago\r\nFROM (\r\n  SELECT\r\n    *,\r\n    ROW_NUMBER() OVER (\r\n      PARTITION BY window_start, gateway\r\n      ORDER BY _loaded_at DESC\r\n    ) AS rn\r\n  FROM `ecommerce-data-platform-497218.ecommerce_streaming.payment_metrics_5min`\r\n  WHERE window_start >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 MINUTE)\r\n)\r\nWHERE rn = 1\r\nGROUP BY window_start\r\nORDER BY window_start ASC"
    }
   ]
  },
  {
   "title": "DLQ Events by Reason",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "project": "ecommerce-data-platform-497218",
     "rawSql": "SELECT\r\n  window_start,\r\n  MAX(CASE WHEN reason = 'invalid_schema' THEN event_count END) AS invalid_schema,\r\n  MAX(CASE WHEN reason = 'late_arrival' THEN event_count END) AS late_arrival\r\nFROM (\r\n  SELECT\r\n    *,\r\n    ROW_NUMBER() OVER (\r\n      PARTITION BY window_start, reason\r\n      ORDER BY _loaded_at DESC\r\n    ) AS rn\r\n  FROM `ecommerce-data-platform-497218.ecommerce_streaming.dlq_metrics_5min`\r\n  WHERE window_start >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 MINUTE)\r\n)\r\nWHERE rn = 1\r\nGROUP BY window_start\r\nORDER BY window_start ASC"
    }
   ]
  }
 ]
}